# Generated by Django 2.2.5 on 2022-02-19 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resevations', '0003_auto_20220218_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='ststus',
            new_name='status',
        ),
    ]
